STEPS = {
    "a": ["awen"],
    "akesi": ["akesi:", "akesi··"],
    "ake": ["akesi·"],
    "ala": ["ala:", "ala·", "alasa·"],
    "alasa": ["alasa:", "alasa··"],
    "ale": ["ale:", "ale·"],
    "anpa": ["anpa:", "anpa··"],
    "an": ["anpa·", "ante·"],
    "ante": ["ante:", "ante··"],
    "anu": ["anu:", "anu·"],
    "awen": ["awen:", "awen··"],
    "awe": ["awen·"],
    "e": ["esun"],
    "en": ["en:", "en·"],
    "esun": ["esun:", "esun··"],
    "esu": ["esun·"],
    "i": ["insa"],
    "ijo": ["ijo:", "ijo·"],
    "ike": ["ike:", "ike·"],
    "ilo": ["ilo:", "ilo·"],
    "insa": ["insa:", "insa··"],
    "in": ["insa·"],
    "j": ["jo"],
    "jaki": ["jaki:", "jaki··"],
    "ja": ["jaki·", "jan·"],
    "jan": ["jan:", "jan··"],
    "jelo": ["jelo:", "jelo··"],
    "je": ["jelo·"],
    "jo": ["jo:", "jo·"],
    "k": ["kute"],
    "kala": ["kala:", "kala··", "kalama··"],
    "ka": ["kala·", "kalama·", "kama·", "kasi·"],
    "kalama": ["kalama:", "kalama···"],
    "kama": ["kama:", "kama··"],
    "kasi": ["kasi:", "kasi··"],
    "ken": ["ken:", "ken··"],
    "ke": ["ken·", "kepeken·"],
    "kepeken": ["kepeken:", "kepeken····"],
    "kepe": ["kepeken··"],
    "kepeke": ["kepeken···"],
    "kijetesantakalu": ["kijetesantakalu:", "kijetesantakalu········"],
    "ki": ["kijetesantakalu·", "kili·", "kin·", "kipisi·", "kiwen·"],
    "kije": ["kijetesantakalu··"],
    "kijete": ["kijetesantakalu···"],
    "kijetesa": ["kijetesantakalu····"],
    "kijetesan": ["kijetesantakalu·····"],
    "kijetesanta": ["kijetesantakalu······"],
    "kijetesantaka": ["kijetesantakalu·······"],
    "kili": ["kili:", "kili··"],
    "kin": ["kin:", "kin··"],
    "kipisi": ["kipisi:", "kipisi···"],
    "kipi": ["kipisi··"],
    "kiwen": ["kiwen:", "kiwen···"],
    "kiwe": ["kiwen··"],
    "ko": ["ko:", "ko·", "kon·"],
    "kon": ["kon:", "kon··"],
    "ku": ["ku:", "ku·", "kule·", "kulupu·", "kute·"],
    "kule": ["kule:", "kule··"],
    "kulupu": ["kulupu:", "kulupu···"],
    "kulu": ["kulupu··"],
    "kute": ["kute:", "kute··"],
    "l": ["lupa"],
    "la": ["la:", "la·", "lanpan·", "lape·", "laso·", "lawa·"],
    "lanpan": ["lanpan:", "lanpan····"],
    "lan": ["lanpan··"],
    "lanpa": ["lanpan···"],
    "lape": ["lape:", "lape··"],
    "laso": ["laso:", "laso··"],
    "lawa": ["lawa:", "lawa··"],
    "leko": ["leko:", "leko··"],
    "le": ["leko·", "len·", "lete·"],
    "len": ["len:", "len··"],
    "lete": ["lete:", "lete··"],
    "li": ["li:", "li·", "lili·", "linja·", "lipu·"],
    "lili": ["lili:", "lili··"],
    "linja": ["linja:", "linja···"],
    "lin": ["linja··"],
    "lipu": ["lipu:", "lipu··"],
    "loje": ["loje:", "loje··"],
    "lo": ["loje·", "lon·"],
    "lon": ["lon:", "lon··"],
    "luka": ["luka:", "luka··"],
    "lu": ["luka·", "lukin·", "lupa·"],
    "lukin": ["lukin:", "lukin···"],
    "luki": ["lukin··"],
    "lupa": ["lupa:", "lupa··"],
    "m": ["mute"],
    "ma": ["ma:", "ma·", "mama·", "mani·"],
    "mama": ["mama:", "mama··"],
    "mani": ["mani:", "mani··"],
    "meli": ["meli:", "meli··"],
    "me": ["meli·", "meso·"],
    "meso": ["meso:", "meso··"],
    "mi": ["mi:", "mi·", "mije·", "misikeke·"],
    "mije": ["mije:", "mije··"],
    "misikeke": ["misikeke:", "misikeke····"],
    "misi": ["misikeke··"],
    "misike": ["misikeke···"],
    "moku": ["moku:", "moku··"],
    "mo": ["moku·", "moli·", "monsi·", "monsuta·"],
    "moli": ["moli:", "moli··"],
    "monsi": ["monsi:", "monsi···"],
    "mon": ["monsi··", "monsuta··"],
    "monsuta": ["monsuta:", "monsuta····"],
    "monsu": ["monsuta···"],
    "mu": ["mu:", "mu·", "mun·", "musi·", "mute·"],
    "mun": ["mun:", "mun··"],
    "musi": ["musi:", "musi··"],
    "mute": ["mute:", "mute··"],
    "n": ["noka"],
    "namako": ["namako:", "namako···"],
    "na": ["namako·", "nanpa·", "nasa·", "nasin·"],
    "nama": ["namako··"],
    "nanpa": ["nanpa:", "nanpa···"],
    "nan": ["nanpa··"],
    "nasa": ["nasa:", "nasa··"],
    "nasin": ["nasin:", "nasin···"],
    "nasi": ["nasin··"],
    "nena": ["nena:", "nena··"],
    "ne": ["nena·"],
    "ni": ["ni:", "ni·", "nimi·"],
    "nimi": ["nimi:", "nimi··"],
    "noka": ["noka:", "noka··"],
    "no": ["noka·"],
    "o": ["open"],
    "oko": ["oko:", "oko·"],
    "olin": ["olin:", "olin··"],
    "oli": ["olin·"],
    "ona": ["ona:", "ona·"],
    "open": ["open:", "open··"],
    "ope": ["open·"],
    "p": ["pu"],
    "pakala": ["pakala:", "pakala···"],
    "pa": ["pakala·", "pali·", "palisa·", "pan·", "pana·"],
    "paka": ["pakala··"],
    "pali": ["pali:", "pali··", "palisa··"],
    "palisa": ["palisa:", "palisa···"],
    "pan": ["pan:", "pan··"],
    "pana": ["pana:", "pana··"],
    "pi": ["pi:", "pi·", "pilin·", "pimeja·", "pini·", "pipi·"],
    "pilin": ["pilin:", "pilin···"],
    "pili": ["pilin··"],
    "pimeja": ["pimeja:", "pimeja···"],
    "pime": ["pimeja··"],
    "pini": ["pini:", "pini··"],
    "pipi": ["pipi:", "pipi··"],
    "poka": ["poka:", "poka··"],
    "po": ["poka·", "poki·", "pona·"],
    "poki": ["poki:", "poki··"],
    "pona": ["pona:", "pona··"],
    "pu": ["pu:", "pu·"],
    "s": ["suwi"],
    "sama": ["sama:", "sama··"],
    "sa": ["sama·"],
    "seli": ["seli:", "seli··"],
    "se": ["seli·", "selo·", "seme·", "sewi·"],
    "selo": ["selo:", "selo··"],
    "seme": ["seme:", "seme··"],
    "sewi": ["sewi:", "sewi··"],
    "sijelo": ["sijelo:", "sijelo···"],
    "si": ["sijelo·", "sike·", "sin·", "sina·", "sinpin·", "sitelen·"],
    "sije": ["sijelo··"],
    "sike": ["sike:", "sike··"],
    "sin": ["sin:", "sin··", "sinpin··"],
    "sina": ["sina:", "sina··"],
    "sinpin": ["sinpin:", "sinpin····"],
    "sinpi": ["sinpin···"],
    "sitelen": ["sitelen:", "sitelen····"],
    "site": ["sitelen··"],
    "sitele": ["sitelen···"],
    "soko": ["soko:", "soko··"],
    "so": ["soko·", "sona·", "soweli·"],
    "sona": ["sona:", "sona··"],
    "soweli": ["soweli:", "soweli···"],
    "sowe": ["soweli··"],
    "suli": ["suli:", "suli··"],
    "su": ["suli·", "suno·", "supa·", "suwi·"],
    "suno": ["suno:", "suno··"],
    "supa": ["supa:", "supa··"],
    "suwi": ["suwi:", "suwi··"],
    "t": ["tu"],
    "tan": ["tan:", "tan··"],
    "ta": ["tan·", "taso·", "tawa·"],
    "taso": ["taso:", "taso··"],
    "tawa": ["tawa:", "tawa··"],
    "telo": ["telo:", "telo··"],
    "te": ["telo·", "tenpo·"],
    "tenpo": ["tenpo:", "tenpo···"],
    "ten": ["tenpo··"],
    "toki": ["toki:", "toki··"],
    "to": ["toki·", "tomo·", "tonsi·"],
    "tomo": ["tomo:", "tomo··"],
    "tonsi": ["tonsi:", "tonsi···"],
    "ton": ["tonsi··"],
    "tu": ["tu:", "tu·"],
    "u": ["utala"],
    "unpa": ["unpa:", "unpa··"],
    "un": ["unpa·"],
    "uta": ["uta:", "uta·", "utala·"],
    "utala": ["utala:", "utala··"],
    "w": ["wile"],
    "walo": ["walo:", "walo··"],
    "wa": ["walo·", "wan·", "waso·", "wawa·"],
    "wan": ["wan:", "wan··"],
    "waso": ["waso:", "waso··"],
    "wawa": ["wawa:", "wawa··"],
    "weka": ["weka:", "weka··"],
    "we": ["weka·"],
    "wile": ["wile:", "wile··"],
    "wi": ["wile·"],
    " ": [" "],
}

BIGSTEPS = {
    "a": ["a", "a:", "akesi", "ala", "alasa", "ale", "anpa", "ante", "anu", "awen"],
    "akesi": ["akesi:", "akesi··"],
    "ake": ["akesi·"],
    "ala": ["ala:", "ala·", "alasa·"],
    "alasa": ["alasa:", "alasa··"],
    "ale": ["ale:", "ale·"],
    "anpa": ["anpa:", "anpa··"],
    "an": ["anpa·", "ante·"],
    "ante": ["ante:", "ante··"],
    "anu": ["anu:", "anu·"],
    "awen": ["awen:", "awen··"],
    "awe": ["awen·"],
    "e": ["e", "e:", "en", "esun"],
    "en": ["en:", "en·"],
    "esun": ["esun:", "esun··"],
    "esu": ["esun·"],
    "i": ["ijo", "ike", "ilo", "insa"],
    "ijo": ["ijo:", "ijo·"],
    "ike": ["ike:", "ike·"],
    "ilo": ["ilo:", "ilo·"],
    "insa": ["insa:", "insa··"],
    "in": ["insa·"],
    "j": ["jaki", "jan", "jelo", "jo"],
    "jaki": ["jaki:", "jaki··"],
    "ja": ["jaki·", "jan·"],
    "jan": ["jan:", "jan··"],
    "jelo": ["jelo:", "jelo··"],
    "je": ["jelo·"],
    "jo": ["jo:", "jo·"],
    "k": [
        "kala",
        "kalama",
        "kama",
        "kasi",
        "ken",
        "kepeken",
        "kijetesantakalu",
        "kili",
        "kin",
        "kipisi",
        "kiwen",
        "ko",
        "kon",
        "ku",
        "kule",
        "kulupu",
        "kute",
    ],
    "kala": ["kala:", "kala··", "kalama··"],
    "ka": ["kala·", "kalama·", "kama·", "kasi·"],
    "kalama": ["kalama:", "kalama···"],
    "kama": ["kama:", "kama··"],
    "kasi": ["kasi:", "kasi··"],
    "ken": ["ken:", "ken··"],
    "ke": ["ken·", "kepeken·"],
    "kepeken": ["kepeken:", "kepeken····"],
    "kepe": ["kepeken··"],
    "kepeke": ["kepeken···"],
    "kijetesantakalu": ["kijetesantakalu:", "kijetesantakalu········"],
    "ki": ["kijetesantakalu·", "kili·", "kin·", "kipisi·", "kiwen·"],
    "kije": ["kijetesantakalu··"],
    "kijete": ["kijetesantakalu···"],
    "kijetesa": ["kijetesantakalu····"],
    "kijetesan": ["kijetesantakalu·····"],
    "kijetesanta": ["kijetesantakalu······"],
    "kijetesantaka": ["kijetesantakalu·······"],
    "kili": ["kili:", "kili··"],
    "kin": ["kin:", "kin··"],
    "kipisi": ["kipisi:", "kipisi···"],
    "kipi": ["kipisi··"],
    "kiwen": ["kiwen:", "kiwen···"],
    "kiwe": ["kiwen··"],
    "ko": ["ko:", "ko·", "kon·"],
    "kon": ["kon:", "kon··"],
    "ku": ["ku:", "ku·", "kule·", "kulupu·", "kute·"],
    "kule": ["kule:", "kule··"],
    "kulupu": ["kulupu:", "kulupu···"],
    "kulu": ["kulupu··"],
    "kute": ["kute:", "kute··"],
    "l": [
        "la",
        "lanpan",
        "lape",
        "laso",
        "lawa",
        "leko",
        "len",
        "lete",
        "li",
        "lili",
        "linja",
        "lipu",
        "loje",
        "lon",
        "luka",
        "lukin",
        "lupa",
    ],
    "la": ["la:", "la·", "lanpan·", "lape·", "laso·", "lawa·"],
    "lanpan": ["lanpan:", "lanpan····"],
    "lan": ["lanpan··"],
    "lanpa": ["lanpan···"],
    "lape": ["lape:", "lape··"],
    "laso": ["laso:", "laso··"],
    "lawa": ["lawa:", "lawa··"],
    "leko": ["leko:", "leko··"],
    "le": ["leko·", "len·", "lete·"],
    "len": ["len:", "len··"],
    "lete": ["lete:", "lete··"],
    "li": ["li:", "li·", "lili·", "linja·", "lipu·"],
    "lili": ["lili:", "lili··"],
    "linja": ["linja:", "linja···"],
    "lin": ["linja··"],
    "lipu": ["lipu:", "lipu··"],
    "loje": ["loje:", "loje··"],
    "lo": ["loje·", "lon·"],
    "lon": ["lon:", "lon··"],
    "luka": ["luka:", "luka··"],
    "lu": ["luka·", "lukin·", "lupa·"],
    "lukin": ["lukin:", "lukin···"],
    "luki": ["lukin··"],
    "lupa": ["lupa:", "lupa··"],
    "m": [
        "ma",
        "mama",
        "mani",
        "meli",
        "meso",
        "mi",
        "mije",
        "misikeke",
        "moku",
        "moli",
        "monsi",
        "monsuta",
        "mu",
        "mun",
        "musi",
        "mute",
    ],
    "ma": ["ma:", "ma·", "mama·", "mani·"],
    "mama": ["mama:", "mama··"],
    "mani": ["mani:", "mani··"],
    "meli": ["meli:", "meli··"],
    "me": ["meli·", "meso·"],
    "meso": ["meso:", "meso··"],
    "mi": ["mi:", "mi·", "mije·", "misikeke·"],
    "mije": ["mije:", "mije··"],
    "misikeke": ["misikeke:", "misikeke····"],
    "misi": ["misikeke··"],
    "misike": ["misikeke···"],
    "moku": ["moku:", "moku··"],
    "mo": ["moku·", "moli·", "monsi·", "monsuta·"],
    "moli": ["moli:", "moli··"],
    "monsi": ["monsi:", "monsi···"],
    "mon": ["monsi··", "monsuta··"],
    "monsuta": ["monsuta:", "monsuta····"],
    "monsu": ["monsuta···"],
    "mu": ["mu:", "mu·", "mun·", "musi·", "mute·"],
    "mun": ["mun:", "mun··"],
    "musi": ["musi:", "musi··"],
    "mute": ["mute:", "mute··"],
    "n": ["n", "n:", "namako", "nanpa", "nasa", "nasin", "nena", "ni", "nimi", "noka"],
    "namako": ["namako:", "namako···"],
    "na": ["namako·", "nanpa·", "nasa·", "nasin·"],
    "nama": ["namako··"],
    "nanpa": ["nanpa:", "nanpa···"],
    "nan": ["nanpa··"],
    "nasa": ["nasa:", "nasa··"],
    "nasin": ["nasin:", "nasin···"],
    "nasi": ["nasin··"],
    "nena": ["nena:", "nena··"],
    "ne": ["nena·"],
    "ni": ["ni:", "ni·", "nimi·"],
    "nimi": ["nimi:", "nimi··"],
    "noka": ["noka:", "noka··"],
    "no": ["noka·"],
    "o": ["o", "o:", "oko", "olin", "ona", "open"],
    "oko": ["oko:", "oko·"],
    "olin": ["olin:", "olin··"],
    "oli": ["olin·"],
    "ona": ["ona:", "ona·"],
    "open": ["open:", "open··"],
    "ope": ["open·"],
    "p": [
        "pakala",
        "pali",
        "palisa",
        "pan",
        "pana",
        "pi",
        "pilin",
        "pimeja",
        "pini",
        "pipi",
        "poka",
        "poki",
        "pona",
        "pu",
    ],
    "pakala": ["pakala:", "pakala···"],
    "pa": ["pakala·", "pali·", "palisa·", "pan·", "pana·"],
    "paka": ["pakala··"],
    "pali": ["pali:", "pali··", "palisa··"],
    "palisa": ["palisa:", "palisa···"],
    "pan": ["pan:", "pan··"],
    "pana": ["pana:", "pana··"],
    "pi": ["pi:", "pi·", "pilin·", "pimeja·", "pini·", "pipi·"],
    "pilin": ["pilin:", "pilin···"],
    "pili": ["pilin··"],
    "pimeja": ["pimeja:", "pimeja···"],
    "pime": ["pimeja··"],
    "pini": ["pini:", "pini··"],
    "pipi": ["pipi:", "pipi··"],
    "poka": ["poka:", "poka··"],
    "po": ["poka·", "poki·", "pona·"],
    "poki": ["poki:", "poki··"],
    "pona": ["pona:", "pona··"],
    "pu": ["pu:", "pu·"],
    "s": [
        "sama",
        "seli",
        "selo",
        "seme",
        "sewi",
        "sijelo",
        "sike",
        "sin",
        "sina",
        "sinpin",
        "sitelen",
        "soko",
        "sona",
        "soweli",
        "suli",
        "suno",
        "supa",
        "suwi",
    ],
    "sama": ["sama:", "sama··"],
    "sa": ["sama·"],
    "seli": ["seli:", "seli··"],
    "se": ["seli·", "selo·", "seme·", "sewi·"],
    "selo": ["selo:", "selo··"],
    "seme": ["seme:", "seme··"],
    "sewi": ["sewi:", "sewi··"],
    "sijelo": ["sijelo:", "sijelo···"],
    "si": ["sijelo·", "sike·", "sin·", "sina·", "sinpin·", "sitelen·"],
    "sije": ["sijelo··"],
    "sike": ["sike:", "sike··"],
    "sin": ["sin:", "sin··", "sinpin··"],
    "sina": ["sina:", "sina··"],
    "sinpin": ["sinpin:", "sinpin····"],
    "sinpi": ["sinpin···"],
    "sitelen": ["sitelen:", "sitelen····"],
    "site": ["sitelen··"],
    "sitele": ["sitelen···"],
    "soko": ["soko:", "soko··"],
    "so": ["soko·", "sona·", "soweli·"],
    "sona": ["sona:", "sona··"],
    "soweli": ["soweli:", "soweli···"],
    "sowe": ["soweli··"],
    "suli": ["suli:", "suli··"],
    "su": ["suli·", "suno·", "supa·", "suwi·"],
    "suno": ["suno:", "suno··"],
    "supa": ["supa:", "supa··"],
    "suwi": ["suwi:", "suwi··"],
    "t": ["tan", "taso", "tawa", "telo", "tenpo", "toki", "tomo", "tonsi", "tu"],
    "tan": ["tan:", "tan··"],
    "ta": ["tan·", "taso·", "tawa·"],
    "taso": ["taso:", "taso··"],
    "tawa": ["tawa:", "tawa··"],
    "telo": ["telo:", "telo··"],
    "te": ["telo·", "tenpo·"],
    "tenpo": ["tenpo:", "tenpo···"],
    "ten": ["tenpo··"],
    "toki": ["toki:", "toki··"],
    "to": ["toki·", "tomo·", "tonsi·"],
    "tomo": ["tomo:", "tomo··"],
    "tonsi": ["tonsi:", "tonsi···"],
    "ton": ["tonsi··"],
    "tu": ["tu:", "tu·"],
    "u": ["unpa", "uta", "utala"],
    "unpa": ["unpa:", "unpa··"],
    "un": ["unpa·"],
    "uta": ["uta:", "uta·", "utala·"],
    "utala": ["utala:", "utala··"],
    "w": ["walo", "wan", "waso", "wawa", "weka", "wile"],
    "walo": ["walo:", "walo··"],
    "wa": ["walo·", "wan·", "waso·", "wawa·"],
    "wan": ["wan:", "wan··"],
    "waso": ["waso:", "waso··"],
    "wawa": ["wawa:", "wawa··"],
    "weka": ["weka:", "weka··"],
    "we": ["weka·"],
    "wile": ["wile:", "wile··"],
    "wi": ["wile·"],
    " ": [" "],
}
